language: python

sudo: false

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"

env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=master

matrix:
    fast_finish: true
    include:
      - python: "3.6"
        env: DJANGO=master
      - python: "3.6"
        env: DJANGO=1.11
      - python: "3.3"
        env: DJANGO=1.8
      - python: "2.7"
        env: TOXENV="lint"
      - python: "2.7"
        env: TOXENV="docs"
    exclude:
      - python: "2.7"
        env: DJANGO=master
      - python: "3.4"
        env: DJANGO=master

    allow_failures:
      - env: DJANGO=1.11
      - env: DJANGO=master

install:
 - pip install -r requirements.txt

 # metlog-py doesn't support Python 3
 - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r optional.txt; fi

 - pip install "Django<${DJANGO}"

script: DJANGO_SETTINGS_MODULE='django_statsd.test_settings' nosetests

notifications:
    email: false
    irc: "irc.mozilla.org#amo-bots"
